# Generated by Django 5.1.2 on 2024-11-04 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('transaction_id', models.AutoField(primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('deposit', 'Deposit'), ('withdrawal', 'Withdrawal'), ('buy_gold', 'Buying Gold'), ('sell_gold', 'Selling Gold')], max_length=20)),
                ('date', models.DateField(auto_now_add=True)),
                ('time', models.TimeField(auto_now_add=True)),
                ('seller', models.CharField(blank=True, max_length=100, null=True)),
                ('rial_amount', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('gold_amount', models.DecimalField(decimal_places=4, max_digits=20, null=True)),
                ('price_per_gram', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
            ],
        ),
    ]
