# Generated by Django 4.2.4 on 2024-10-17 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('User_ID', models.BigIntegerField(primary_key=True, serialize=False)),
                ('phone_number', models.CharField(max_length=14)),
                ('address', models.TextField()),
                ('password', models.CharField(max_length=30)),
                ('user_type', models.IntegerField()),
                ('national_ID', models.CharField(max_length=10)),
                ('birthdate', models.DateField()),
                ('rial_balance', models.CharField(max_length=10)),
                ('gold_balance', models.CharField(max_length=10)),
            ],
        ),
    ]
