# Generated by Django 5.1.2 on 2024-11-02 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userprofile_remove_user_address_remove_user_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBankInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_no', models.PositiveIntegerField()),
                ('sheba', models.PositiveIntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
        migrations.AddField(
            model_name='user',
            name='full_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
