# Generated by Django 5.1.2 on 2024-11-03 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_userbankinfo_delete_userprofile_user_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbankinfo',
            name='cart_no',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userbankinfo',
            name='sheba',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
