# Generated by Django 4.2.4 on 2024-10-17 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_account_address_alter_account_birthdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='national_ID',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
