# Generated by Django 5.1.2 on 2024-11-03 11:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_userbankinfo_cart_no_alter_userbankinfo_sheba'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbankinfo',
            name='user',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userbankinfo',
            name='cart_no',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='userbankinfo',
            name='sheba',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
