# Generated by Django 5.1.2 on 2024-11-03 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_userbankinfo_user_alter_userbankinfo_cart_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbankinfo',
            name='cart_no',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userbankinfo',
            name='sheba',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
