# Generated by Django 5.1.2 on 2024-11-03 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_userbankinfo_cart_no_alter_userbankinfo_sheba'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbankinfo',
            name='cart_no',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='userbankinfo',
            name='sheba',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
